### ISSUE TITLE
Plotting of voltage traces not working when using format (pop, index) on multiple cores 

### ISSUE THREAD

**Issue by salvadord** [Neurosim-lab/netpyne#446]

**Comment by salvadord** [comment]
@jjcarre did you get a chance to look at this? (not sure if I mentioned)

**Comment by jjcarre** [comment]
Yes I made a pull request for iss446. The problem was in sim/utils.py getCellsList, where the function would get the cells for a certain pop from all the nodes but not order them by gid. So, the 0 index cell would be the lowest gid on node 0 rather than the lowest gid overall, then later the saved traces didn't match that gid.

**Comment by salvadord** [comment]
ok, great, so I'll close this issue, thanks!
